### ISSUE TITLE
[BUG] Bull Skull Masks don't drop when broken or have world gen.

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Darkhax/Bone-Zone#14]
### Minecraft Version

1.20.1

### Mod Version

3.0.4

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

When breaking the bull skull mask once placed, it doesn't drop, just disappears. I haven't found it in the world either but figured it was just rare.

**Comment by Darkhax** [comment]
Thanks for letting us know about this issue. I've uploaded a fix for both of these issues and it's currently being processed by CurseForge. You can find [3.0.5 here](https://www.curseforge.com/minecraft/mc-mods/bone-zone/files/5164224) once it's processed. 

 The bull carcass can be found in the following biomes.
 - stony shore
 - dark forest
 - badlands
 - eroded badlands
 - river
 - savanna plateau
