### ISSUE TITLE
Mobs don't avoid the bone cutter

### ISSUE THREAD

**Issue by ChiefArug** [Darkhax/Bone-Zone#8]
Unplayable. My poor puppy
![Wolf death message](https://cdn.discordapp.com/attachments/1029506749939580988/1040391276215931001/image.png)

Would be great if they avoided pathfinding over it, like mobs do for magma blocks and fire.

**Comment by Trikzon** [comment]
😭

**Comment by Darkhax** [comment]
This has finally been implemented. Unfortunately Mojang hardcodes pathfinding types so this required some new mixins.
